### ISSUE TITLE
Error if LOG_DYNAMIC_LEVEL_CONTROL is not set (TZ-2370)

### ISSUE THREAD

**Issue by luar123** [espressif/esp-zboss-lib#8]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

check CONFIG_LOG_DYNAMIC_LEVEL_CONTROL before calling esp_log_default_level

### Actual behavior (suspected bug)

When CONFIG_LOG_DYNAMIC_LEVEL_CONTROL=false the compilation fails with
```
riscv32-esp-elf/bin/ld: managed_components/espressif__esp-zigbee-lib/lib/esp32c6/libzboss_port.native.a(zb_esp_mac.c.obj): in function `esp_ieee802154_transmit_failed':
(.iram1.4+0xc2): undefined reference to `esp_log_default_level'
/home/runner/.platformio/packages/toolchain-riscv32-esp/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: (.iram1.4+0xc6): undefined reference to `esp_log_default_level'
```

### Error logs or terminal output

```shell

```

### Steps to reproduce the behavior

1. set CONFIG_LOG_DYNAMIC_LEVEL_CONTROL=false in sdkconfig
2. compile any example

### Project release version

latest

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

any

### Shell

Bash

**Comment by luar123** [comment]
@xieqinan Any chance to get this fixed?

**Comment by xieqinan** [comment]
The issue seems to be related to the ESP-IDF version. Could you please test it using the recommended versions of **ESP Zigbee SDK** and **ESP-IDF** listed in the [official documentation](https://github.com/espressif/esp-zigbee-sdk?tab=readme-ov-file#supported-esp-idf-versions)?

**Comment by luar123** [comment]
Thanks, yes it works with 5.3.2, but I could not test v6.0 beta yet as the project is not compatible. Any plans to fix it for newer versions? 5.3 maintenance period is less than a year from now.

**Comment by luar123** [comment]
@xieqinan It also fails with v6.0-rc1 which is needed for esp32c5.
